# Generated by Django 6.0.5 on 2026-05-20 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experimentdata',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('anomaly', 'Noise / Anomaly'), ('retest', 'Needs Retest')], default='success', max_length=20),
        ),
    ]
